#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentification
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ProjetBDD")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertAuth(Auth instance);
    partial void UpdateAuth(Auth instance);
    partial void DeleteAuth(Auth instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    partial void InsertEntretien(Entretien instance);
    partial void UpdateEntretien(Entretien instance);
    partial void DeleteEntretien(Entretien instance);
    partial void InsertRecrutement(Recrutement instance);
    partial void UpdateRecrutement(Recrutement instance);
    partial void DeleteRecrutement(Recrutement instance);
    partial void Insertinfo_entreprise(info_entreprise instance);
    partial void Updateinfo_entreprise(info_entreprise instance);
    partial void Deleteinfo_entreprise(info_entreprise instance);
    partial void Insertinfo_comp(info_comp instance);
    partial void Updateinfo_comp(info_comp instance);
    partial void Deleteinfo_comp(info_comp instance);
    partial void Insertobjectif(objectif instance);
    partial void Updateobjectif(objectif instance);
    partial void Deleteobjectif(objectif instance);
    partial void InsertSalaire(Salaire instance);
    partial void UpdateSalaire(Salaire instance);
    partial void DeleteSalaire(Salaire instance);
    partial void Insertcongé2(congé2 instance);
    partial void Updatecongé2(congé2 instance);
    partial void Deletecongé2(congé2 instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Authentification.Properties.Settings.Default.ProjetBDDConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Auth> Auth
		{
			get
			{
				return this.GetTable<Auth>();
			}
		}
		
		public System.Data.Linq.Table<Employee> Employee
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
		
		public System.Data.Linq.Table<Entretien> Entretien
		{
			get
			{
				return this.GetTable<Entretien>();
			}
		}
		
		public System.Data.Linq.Table<Recrutement> Recrutement
		{
			get
			{
				return this.GetTable<Recrutement>();
			}
		}
		
		public System.Data.Linq.Table<info_entreprise> info_entreprise
		{
			get
			{
				return this.GetTable<info_entreprise>();
			}
		}
		
		public System.Data.Linq.Table<info_comp> info_comp
		{
			get
			{
				return this.GetTable<info_comp>();
			}
		}
		
		public System.Data.Linq.Table<objectif> objectif
		{
			get
			{
				return this.GetTable<objectif>();
			}
		}
		
		public System.Data.Linq.Table<Salaire> Salaire
		{
			get
			{
				return this.GetTable<Salaire>();
			}
		}
		
		public System.Data.Linq.Table<congé2> congé2
		{
			get
			{
				return this.GetTable<congé2>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Auth")]
	public partial class Auth : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _user;
		
		private string _password;
		
		private System.Nullable<int> _profil_admin;
		
		private System.Nullable<int> _profil_gest;
		
		private string _couleur;
		
		private string _theme;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnuserChanging(string value);
    partial void OnuserChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onprofil_adminChanging(System.Nullable<int> value);
    partial void Onprofil_adminChanged();
    partial void Onprofil_gestChanging(System.Nullable<int> value);
    partial void Onprofil_gestChanged();
    partial void OncouleurChanging(string value);
    partial void OncouleurChanged();
    partial void OnthemeChanging(string value);
    partial void OnthemeChanged();
    #endregion
		
		public Auth()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[user]", Storage="_user", DbType="VarChar(MAX)")]
		public string user
		{
			get
			{
				return this._user;
			}
			set
			{
				if ((this._user != value))
				{
					this.OnuserChanging(value);
					this.SendPropertyChanging();
					this._user = value;
					this.SendPropertyChanged("user");
					this.OnuserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(MAX)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profil_admin", DbType="Int")]
		public System.Nullable<int> profil_admin
		{
			get
			{
				return this._profil_admin;
			}
			set
			{
				if ((this._profil_admin != value))
				{
					this.Onprofil_adminChanging(value);
					this.SendPropertyChanging();
					this._profil_admin = value;
					this.SendPropertyChanged("profil_admin");
					this.Onprofil_adminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profil_gest", DbType="Int")]
		public System.Nullable<int> profil_gest
		{
			get
			{
				return this._profil_gest;
			}
			set
			{
				if ((this._profil_gest != value))
				{
					this.Onprofil_gestChanging(value);
					this.SendPropertyChanging();
					this._profil_gest = value;
					this.SendPropertyChanged("profil_gest");
					this.Onprofil_gestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_couleur", DbType="VarChar(MAX)")]
		public string couleur
		{
			get
			{
				return this._couleur;
			}
			set
			{
				if ((this._couleur != value))
				{
					this.OncouleurChanging(value);
					this.SendPropertyChanging();
					this._couleur = value;
					this.SendPropertyChanged("couleur");
					this.OncouleurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_theme", DbType="VarChar(MAX)")]
		public string theme
		{
			get
			{
				return this._theme;
			}
			set
			{
				if ((this._theme != value))
				{
					this.OnthemeChanging(value);
					this.SendPropertyChanging();
					this._theme = value;
					this.SendPropertyChanged("theme");
					this.OnthemeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _matricule;
		
		private string _nom;
		
		private string _prenom;
		
		private System.Nullable<System.DateTime> _Date_de_ness;
		
		private string _Adresse;
		
		private System.Nullable<long> _Num_tel;
		
		private string _Adr_mail;
		
		private string _Cor_bnc;
		
		private string _wilaya_naiss;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatriculeChanging(int value);
    partial void OnmatriculeChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OnDate_de_nessChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_de_nessChanged();
    partial void OnAdresseChanging(string value);
    partial void OnAdresseChanged();
    partial void OnNum_telChanging(System.Nullable<long> value);
    partial void OnNum_telChanged();
    partial void OnAdr_mailChanging(string value);
    partial void OnAdr_mailChanged();
    partial void OnCor_bncChanging(string value);
    partial void OnCor_bncChanged();
    partial void Onwilaya_naissChanging(string value);
    partial void Onwilaya_naissChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricule", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int matricule
		{
			get
			{
				return this._matricule;
			}
			set
			{
				if ((this._matricule != value))
				{
					this.OnmatriculeChanging(value);
					this.SendPropertyChanging();
					this._matricule = value;
					this.SendPropertyChanged("matricule");
					this.OnmatriculeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(MAX)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(MAX)")]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_de_ness", DbType="Date")]
		public System.Nullable<System.DateTime> Date_de_ness
		{
			get
			{
				return this._Date_de_ness;
			}
			set
			{
				if ((this._Date_de_ness != value))
				{
					this.OnDate_de_nessChanging(value);
					this.SendPropertyChanging();
					this._Date_de_ness = value;
					this.SendPropertyChanged("Date_de_ness");
					this.OnDate_de_nessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adresse", DbType="VarChar(MAX)")]
		public string Adresse
		{
			get
			{
				return this._Adresse;
			}
			set
			{
				if ((this._Adresse != value))
				{
					this.OnAdresseChanging(value);
					this.SendPropertyChanging();
					this._Adresse = value;
					this.SendPropertyChanged("Adresse");
					this.OnAdresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_tel", DbType="BigInt")]
		public System.Nullable<long> Num_tel
		{
			get
			{
				return this._Num_tel;
			}
			set
			{
				if ((this._Num_tel != value))
				{
					this.OnNum_telChanging(value);
					this.SendPropertyChanging();
					this._Num_tel = value;
					this.SendPropertyChanged("Num_tel");
					this.OnNum_telChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adr_mail", DbType="VarChar(MAX)")]
		public string Adr_mail
		{
			get
			{
				return this._Adr_mail;
			}
			set
			{
				if ((this._Adr_mail != value))
				{
					this.OnAdr_mailChanging(value);
					this.SendPropertyChanging();
					this._Adr_mail = value;
					this.SendPropertyChanged("Adr_mail");
					this.OnAdr_mailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cor_bnc", DbType="VarChar(MAX)")]
		public string Cor_bnc
		{
			get
			{
				return this._Cor_bnc;
			}
			set
			{
				if ((this._Cor_bnc != value))
				{
					this.OnCor_bncChanging(value);
					this.SendPropertyChanging();
					this._Cor_bnc = value;
					this.SendPropertyChanged("Cor_bnc");
					this.OnCor_bncChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wilaya_naiss", DbType="VarChar(MAX)")]
		public string wilaya_naiss
		{
			get
			{
				return this._wilaya_naiss;
			}
			set
			{
				if ((this._wilaya_naiss != value))
				{
					this.Onwilaya_naissChanging(value);
					this.SendPropertyChanging();
					this._wilaya_naiss = value;
					this.SendPropertyChanged("wilaya_naiss");
					this.Onwilaya_naissChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Entretien")]
	public partial class Entretien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _matricule;
		
		private string _exp;
		
		private string _Q1;
		
		private System.Nullable<int> _evaQ1;
		
		private string _Q2;
		
		private System.Nullable<int> _evaQ2;
		
		private System.Nullable<System.DateTime> _date;
		
		private System.Nullable<int> _salaire_des;
		
		private string _statut;
		
		private string _etape_suiv;
		
		private string _comment;
		
		private int _id;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatriculeChanging(int value);
    partial void OnmatriculeChanged();
    partial void OnexpChanging(string value);
    partial void OnexpChanged();
    partial void OnQ1Changing(string value);
    partial void OnQ1Changed();
    partial void OnevaQ1Changing(System.Nullable<int> value);
    partial void OnevaQ1Changed();
    partial void OnQ2Changing(string value);
    partial void OnQ2Changed();
    partial void OnevaQ2Changing(System.Nullable<int> value);
    partial void OnevaQ2Changed();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void Onsalaire_desChanging(System.Nullable<int> value);
    partial void Onsalaire_desChanged();
    partial void OnstatutChanging(string value);
    partial void OnstatutChanged();
    partial void Onetape_suivChanging(string value);
    partial void Onetape_suivChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public Entretien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricule", DbType="Int NOT NULL")]
		public int matricule
		{
			get
			{
				return this._matricule;
			}
			set
			{
				if ((this._matricule != value))
				{
					this.OnmatriculeChanging(value);
					this.SendPropertyChanging();
					this._matricule = value;
					this.SendPropertyChanged("matricule");
					this.OnmatriculeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exp", DbType="VarChar(MAX)")]
		public string exp
		{
			get
			{
				return this._exp;
			}
			set
			{
				if ((this._exp != value))
				{
					this.OnexpChanging(value);
					this.SendPropertyChanging();
					this._exp = value;
					this.SendPropertyChanged("exp");
					this.OnexpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Q1", DbType="VarChar(MAX)")]
		public string Q1
		{
			get
			{
				return this._Q1;
			}
			set
			{
				if ((this._Q1 != value))
				{
					this.OnQ1Changing(value);
					this.SendPropertyChanging();
					this._Q1 = value;
					this.SendPropertyChanged("Q1");
					this.OnQ1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evaQ1", DbType="Int")]
		public System.Nullable<int> evaQ1
		{
			get
			{
				return this._evaQ1;
			}
			set
			{
				if ((this._evaQ1 != value))
				{
					this.OnevaQ1Changing(value);
					this.SendPropertyChanging();
					this._evaQ1 = value;
					this.SendPropertyChanged("evaQ1");
					this.OnevaQ1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Q2", DbType="VarChar(MAX)")]
		public string Q2
		{
			get
			{
				return this._Q2;
			}
			set
			{
				if ((this._Q2 != value))
				{
					this.OnQ2Changing(value);
					this.SendPropertyChanging();
					this._Q2 = value;
					this.SendPropertyChanged("Q2");
					this.OnQ2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evaQ2", DbType="Int")]
		public System.Nullable<int> evaQ2
		{
			get
			{
				return this._evaQ2;
			}
			set
			{
				if ((this._evaQ2 != value))
				{
					this.OnevaQ2Changing(value);
					this.SendPropertyChanging();
					this._evaQ2 = value;
					this.SendPropertyChanged("evaQ2");
					this.OnevaQ2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salaire_des", DbType="Int")]
		public System.Nullable<int> salaire_des
		{
			get
			{
				return this._salaire_des;
			}
			set
			{
				if ((this._salaire_des != value))
				{
					this.Onsalaire_desChanging(value);
					this.SendPropertyChanging();
					this._salaire_des = value;
					this.SendPropertyChanged("salaire_des");
					this.Onsalaire_desChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statut", DbType="VarChar(MAX)")]
		public string statut
		{
			get
			{
				return this._statut;
			}
			set
			{
				if ((this._statut != value))
				{
					this.OnstatutChanging(value);
					this.SendPropertyChanging();
					this._statut = value;
					this.SendPropertyChanged("statut");
					this.OnstatutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etape_suiv", DbType="VarChar(MAX)")]
		public string etape_suiv
		{
			get
			{
				return this._etape_suiv;
			}
			set
			{
				if ((this._etape_suiv != value))
				{
					this.Onetape_suivChanging(value);
					this.SendPropertyChanging();
					this._etape_suiv = value;
					this.SendPropertyChanged("etape_suiv");
					this.Onetape_suivChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="VarChar(MAX)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recrutement")]
	public partial class Recrutement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _matricule;
		
		private string _nom_dm;
		
		private System.Nullable<int> _num;
		
		private string _Adr_mail;
		
		private string _int_post;
		
		private System.Nullable<System.DateTime> _date_ent_;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatriculeChanging(int value);
    partial void OnmatriculeChanged();
    partial void Onnom_dmChanging(string value);
    partial void Onnom_dmChanged();
    partial void OnnumChanging(System.Nullable<int> value);
    partial void OnnumChanged();
    partial void OnAdr_mailChanging(string value);
    partial void OnAdr_mailChanged();
    partial void Onint_postChanging(string value);
    partial void Onint_postChanged();
    partial void Ondate_ent_Changing(System.Nullable<System.DateTime> value);
    partial void Ondate_ent_Changed();
    #endregion
		
		public Recrutement()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricule", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int matricule
		{
			get
			{
				return this._matricule;
			}
			set
			{
				if ((this._matricule != value))
				{
					this.OnmatriculeChanging(value);
					this.SendPropertyChanging();
					this._matricule = value;
					this.SendPropertyChanged("matricule");
					this.OnmatriculeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_dm", DbType="VarChar(MAX)")]
		public string nom_dm
		{
			get
			{
				return this._nom_dm;
			}
			set
			{
				if ((this._nom_dm != value))
				{
					this.Onnom_dmChanging(value);
					this.SendPropertyChanging();
					this._nom_dm = value;
					this.SendPropertyChanged("nom_dm");
					this.Onnom_dmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num", DbType="Int")]
		public System.Nullable<int> num
		{
			get
			{
				return this._num;
			}
			set
			{
				if ((this._num != value))
				{
					this.OnnumChanging(value);
					this.SendPropertyChanging();
					this._num = value;
					this.SendPropertyChanged("num");
					this.OnnumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adr_mail", DbType="VarChar(50)")]
		public string Adr_mail
		{
			get
			{
				return this._Adr_mail;
			}
			set
			{
				if ((this._Adr_mail != value))
				{
					this.OnAdr_mailChanging(value);
					this.SendPropertyChanging();
					this._Adr_mail = value;
					this.SendPropertyChanged("Adr_mail");
					this.OnAdr_mailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_int_post", DbType="VarChar(MAX)")]
		public string int_post
		{
			get
			{
				return this._int_post;
			}
			set
			{
				if ((this._int_post != value))
				{
					this.Onint_postChanging(value);
					this.SendPropertyChanging();
					this._int_post = value;
					this.SendPropertyChanged("int_post");
					this.Onint_postChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[date_ent ]", Storage="_date_ent_", DbType="Date")]
		public System.Nullable<System.DateTime> date_ent_
		{
			get
			{
				return this._date_ent_;
			}
			set
			{
				if ((this._date_ent_ != value))
				{
					this.Ondate_ent_Changing(value);
					this.SendPropertyChanging();
					this._date_ent_ = value;
					this.SendPropertyChanged("date_ent_");
					this.Ondate_ent_Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.info_entreprise")]
	public partial class info_entreprise : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Raison_so;
		
		private string _Spécialité;
		
		private string _site_web;
		
		private string _Gérant;
		
		private string _Adr;
		
		private System.Nullable<long> _Téléphone;
		
		private System.Nullable<long> _Fax;
		
		private string _Adr_mail_g;
		
		private System.Nullable<long> _Numéro_RC;
		
		private string _identifiant_fi;
		
		private System.Data.Linq.Binary _Logo;
		
		private string _wilaya;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnRaison_soChanging(string value);
    partial void OnRaison_soChanged();
    partial void OnSpécialitéChanging(string value);
    partial void OnSpécialitéChanged();
    partial void Onsite_webChanging(string value);
    partial void Onsite_webChanged();
    partial void OnGérantChanging(string value);
    partial void OnGérantChanged();
    partial void OnAdrChanging(string value);
    partial void OnAdrChanged();
    partial void OnTéléphoneChanging(System.Nullable<long> value);
    partial void OnTéléphoneChanged();
    partial void OnFaxChanging(System.Nullable<long> value);
    partial void OnFaxChanged();
    partial void OnAdr_mail_gChanging(string value);
    partial void OnAdr_mail_gChanged();
    partial void OnNuméro_RCChanging(System.Nullable<long> value);
    partial void OnNuméro_RCChanged();
    partial void Onidentifiant_fiChanging(string value);
    partial void Onidentifiant_fiChanged();
    partial void OnLogoChanging(System.Data.Linq.Binary value);
    partial void OnLogoChanged();
    partial void OnwilayaChanging(string value);
    partial void OnwilayaChanged();
    #endregion
		
		public info_entreprise()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Raison_so", DbType="VarChar(MAX)")]
		public string Raison_so
		{
			get
			{
				return this._Raison_so;
			}
			set
			{
				if ((this._Raison_so != value))
				{
					this.OnRaison_soChanging(value);
					this.SendPropertyChanging();
					this._Raison_so = value;
					this.SendPropertyChanged("Raison_so");
					this.OnRaison_soChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Spécialité", DbType="VarChar(MAX)")]
		public string Spécialité
		{
			get
			{
				return this._Spécialité;
			}
			set
			{
				if ((this._Spécialité != value))
				{
					this.OnSpécialitéChanging(value);
					this.SendPropertyChanging();
					this._Spécialité = value;
					this.SendPropertyChanged("Spécialité");
					this.OnSpécialitéChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_site_web", DbType="VarChar(MAX)")]
		public string site_web
		{
			get
			{
				return this._site_web;
			}
			set
			{
				if ((this._site_web != value))
				{
					this.Onsite_webChanging(value);
					this.SendPropertyChanging();
					this._site_web = value;
					this.SendPropertyChanged("site_web");
					this.Onsite_webChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gérant", DbType="VarChar(MAX)")]
		public string Gérant
		{
			get
			{
				return this._Gérant;
			}
			set
			{
				if ((this._Gérant != value))
				{
					this.OnGérantChanging(value);
					this.SendPropertyChanging();
					this._Gérant = value;
					this.SendPropertyChanged("Gérant");
					this.OnGérantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adr", DbType="VarChar(MAX)")]
		public string Adr
		{
			get
			{
				return this._Adr;
			}
			set
			{
				if ((this._Adr != value))
				{
					this.OnAdrChanging(value);
					this.SendPropertyChanging();
					this._Adr = value;
					this.SendPropertyChanged("Adr");
					this.OnAdrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Téléphone", DbType="BigInt")]
		public System.Nullable<long> Téléphone
		{
			get
			{
				return this._Téléphone;
			}
			set
			{
				if ((this._Téléphone != value))
				{
					this.OnTéléphoneChanging(value);
					this.SendPropertyChanging();
					this._Téléphone = value;
					this.SendPropertyChanged("Téléphone");
					this.OnTéléphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="BigInt")]
		public System.Nullable<long> Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adr_mail_g", DbType="VarChar(MAX)")]
		public string Adr_mail_g
		{
			get
			{
				return this._Adr_mail_g;
			}
			set
			{
				if ((this._Adr_mail_g != value))
				{
					this.OnAdr_mail_gChanging(value);
					this.SendPropertyChanging();
					this._Adr_mail_g = value;
					this.SendPropertyChanged("Adr_mail_g");
					this.OnAdr_mail_gChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numéro_RC", DbType="BigInt")]
		public System.Nullable<long> Numéro_RC
		{
			get
			{
				return this._Numéro_RC;
			}
			set
			{
				if ((this._Numéro_RC != value))
				{
					this.OnNuméro_RCChanging(value);
					this.SendPropertyChanging();
					this._Numéro_RC = value;
					this.SendPropertyChanged("Numéro_RC");
					this.OnNuméro_RCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identifiant_fi", DbType="VarChar(MAX)")]
		public string identifiant_fi
		{
			get
			{
				return this._identifiant_fi;
			}
			set
			{
				if ((this._identifiant_fi != value))
				{
					this.Onidentifiant_fiChanging(value);
					this.SendPropertyChanging();
					this._identifiant_fi = value;
					this.SendPropertyChanged("identifiant_fi");
					this.Onidentifiant_fiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this.OnLogoChanging(value);
					this.SendPropertyChanging();
					this._Logo = value;
					this.SendPropertyChanged("Logo");
					this.OnLogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wilaya", DbType="VarChar(MAX)")]
		public string wilaya
		{
			get
			{
				return this._wilaya;
			}
			set
			{
				if ((this._wilaya != value))
				{
					this.OnwilayaChanging(value);
					this.SendPropertyChanging();
					this._wilaya = value;
					this.SendPropertyChanged("wilaya");
					this.OnwilayaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.info_comp")]
	public partial class info_comp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _matricule;
		
		private string _situ_fam;
		
		private System.Nullable<System.DateTime> _Date_emb;
		
		private System.Nullable<decimal> _salaire;
		
		private string _NIS;
		
		private System.Data.Linq.Binary _C_T;
		
		private System.Data.Linq.Binary _CV;
		
		private string _statut;
		
		private System.Nullable<System.DateTime> _Date_dem;
		
		private string _poste;
		
		private string _projet;
		
		private System.Nullable<int> _Nbj_r_c;
		
		private string _comment;
		
		private string _respo;
		
		private string _sex;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatriculeChanging(int value);
    partial void OnmatriculeChanged();
    partial void Onsitu_famChanging(string value);
    partial void Onsitu_famChanged();
    partial void OnDate_embChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_embChanged();
    partial void OnsalaireChanging(System.Nullable<decimal> value);
    partial void OnsalaireChanged();
    partial void OnNISChanging(string value);
    partial void OnNISChanged();
    partial void OnC_TChanging(System.Data.Linq.Binary value);
    partial void OnC_TChanged();
    partial void OnCVChanging(System.Data.Linq.Binary value);
    partial void OnCVChanged();
    partial void OnstatutChanging(string value);
    partial void OnstatutChanged();
    partial void OnDate_demChanging(System.Nullable<System.DateTime> value);
    partial void OnDate_demChanged();
    partial void OnposteChanging(string value);
    partial void OnposteChanged();
    partial void OnprojetChanging(string value);
    partial void OnprojetChanged();
    partial void OnNbj_r_cChanging(System.Nullable<int> value);
    partial void OnNbj_r_cChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OnrespoChanging(string value);
    partial void OnrespoChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    #endregion
		
		public info_comp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricule", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int matricule
		{
			get
			{
				return this._matricule;
			}
			set
			{
				if ((this._matricule != value))
				{
					this.OnmatriculeChanging(value);
					this.SendPropertyChanging();
					this._matricule = value;
					this.SendPropertyChanged("matricule");
					this.OnmatriculeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_situ_fam", DbType="VarChar(MAX)")]
		public string situ_fam
		{
			get
			{
				return this._situ_fam;
			}
			set
			{
				if ((this._situ_fam != value))
				{
					this.Onsitu_famChanging(value);
					this.SendPropertyChanging();
					this._situ_fam = value;
					this.SendPropertyChanged("situ_fam");
					this.Onsitu_famChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_emb", DbType="Date")]
		public System.Nullable<System.DateTime> Date_emb
		{
			get
			{
				return this._Date_emb;
			}
			set
			{
				if ((this._Date_emb != value))
				{
					this.OnDate_embChanging(value);
					this.SendPropertyChanging();
					this._Date_emb = value;
					this.SendPropertyChanged("Date_emb");
					this.OnDate_embChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salaire", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> salaire
		{
			get
			{
				return this._salaire;
			}
			set
			{
				if ((this._salaire != value))
				{
					this.OnsalaireChanging(value);
					this.SendPropertyChanging();
					this._salaire = value;
					this.SendPropertyChanged("salaire");
					this.OnsalaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIS", DbType="VarChar(MAX)")]
		public string NIS
		{
			get
			{
				return this._NIS;
			}
			set
			{
				if ((this._NIS != value))
				{
					this.OnNISChanging(value);
					this.SendPropertyChanging();
					this._NIS = value;
					this.SendPropertyChanged("NIS");
					this.OnNISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_T", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary C_T
		{
			get
			{
				return this._C_T;
			}
			set
			{
				if ((this._C_T != value))
				{
					this.OnC_TChanging(value);
					this.SendPropertyChanging();
					this._C_T = value;
					this.SendPropertyChanged("C_T");
					this.OnC_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CV", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary CV
		{
			get
			{
				return this._CV;
			}
			set
			{
				if ((this._CV != value))
				{
					this.OnCVChanging(value);
					this.SendPropertyChanging();
					this._CV = value;
					this.SendPropertyChanged("CV");
					this.OnCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statut", DbType="VarChar(MAX)")]
		public string statut
		{
			get
			{
				return this._statut;
			}
			set
			{
				if ((this._statut != value))
				{
					this.OnstatutChanging(value);
					this.SendPropertyChanging();
					this._statut = value;
					this.SendPropertyChanged("statut");
					this.OnstatutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_dem", DbType="Date")]
		public System.Nullable<System.DateTime> Date_dem
		{
			get
			{
				return this._Date_dem;
			}
			set
			{
				if ((this._Date_dem != value))
				{
					this.OnDate_demChanging(value);
					this.SendPropertyChanging();
					this._Date_dem = value;
					this.SendPropertyChanged("Date_dem");
					this.OnDate_demChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_poste", DbType="VarChar(MAX)")]
		public string poste
		{
			get
			{
				return this._poste;
			}
			set
			{
				if ((this._poste != value))
				{
					this.OnposteChanging(value);
					this.SendPropertyChanging();
					this._poste = value;
					this.SendPropertyChanged("poste");
					this.OnposteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_projet", DbType="VarChar(MAX)")]
		public string projet
		{
			get
			{
				return this._projet;
			}
			set
			{
				if ((this._projet != value))
				{
					this.OnprojetChanging(value);
					this.SendPropertyChanging();
					this._projet = value;
					this.SendPropertyChanged("projet");
					this.OnprojetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nbj_r_c", DbType="Int")]
		public System.Nullable<int> Nbj_r_c
		{
			get
			{
				return this._Nbj_r_c;
			}
			set
			{
				if ((this._Nbj_r_c != value))
				{
					this.OnNbj_r_cChanging(value);
					this.SendPropertyChanging();
					this._Nbj_r_c = value;
					this.SendPropertyChanged("Nbj_r_c");
					this.OnNbj_r_cChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="VarChar(MAX)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this.OncommentChanging(value);
					this.SendPropertyChanging();
					this._comment = value;
					this.SendPropertyChanged("comment");
					this.OncommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_respo", DbType="VarChar(MAX)")]
		public string respo
		{
			get
			{
				return this._respo;
			}
			set
			{
				if ((this._respo != value))
				{
					this.OnrespoChanging(value);
					this.SendPropertyChanging();
					this._respo = value;
					this.SendPropertyChanged("respo");
					this.OnrespoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="VarChar(MAX)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.objectif")]
	public partial class objectif : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _matricule;
		
		private string _o;
		
		private System.Nullable<System.DateTime> _debut;
		
		private System.Nullable<System.DateTime> _fin;
		
		private int _clé;
		
		private System.Nullable<int> _eva;
		
		private string _type;
		
		private string _eval;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatriculeChanging(System.Nullable<int> value);
    partial void OnmatriculeChanged();
    partial void OnoChanging(string value);
    partial void OnoChanged();
    partial void OndebutChanging(System.Nullable<System.DateTime> value);
    partial void OndebutChanged();
    partial void OnfinChanging(System.Nullable<System.DateTime> value);
    partial void OnfinChanged();
    partial void OncléChanging(int value);
    partial void OncléChanged();
    partial void OnevaChanging(System.Nullable<int> value);
    partial void OnevaChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnevalChanging(string value);
    partial void OnevalChanged();
    #endregion
		
		public objectif()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricule", DbType="Int")]
		public System.Nullable<int> matricule
		{
			get
			{
				return this._matricule;
			}
			set
			{
				if ((this._matricule != value))
				{
					this.OnmatriculeChanging(value);
					this.SendPropertyChanging();
					this._matricule = value;
					this.SendPropertyChanged("matricule");
					this.OnmatriculeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o", DbType="VarChar(MAX)")]
		public string o
		{
			get
			{
				return this._o;
			}
			set
			{
				if ((this._o != value))
				{
					this.OnoChanging(value);
					this.SendPropertyChanging();
					this._o = value;
					this.SendPropertyChanged("o");
					this.OnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_debut", DbType="Date")]
		public System.Nullable<System.DateTime> debut
		{
			get
			{
				return this._debut;
			}
			set
			{
				if ((this._debut != value))
				{
					this.OndebutChanging(value);
					this.SendPropertyChanging();
					this._debut = value;
					this.SendPropertyChanged("debut");
					this.OndebutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fin", DbType="Date")]
		public System.Nullable<System.DateTime> fin
		{
			get
			{
				return this._fin;
			}
			set
			{
				if ((this._fin != value))
				{
					this.OnfinChanging(value);
					this.SendPropertyChanging();
					this._fin = value;
					this.SendPropertyChanged("fin");
					this.OnfinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clé", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int clé
		{
			get
			{
				return this._clé;
			}
			set
			{
				if ((this._clé != value))
				{
					this.OncléChanging(value);
					this.SendPropertyChanging();
					this._clé = value;
					this.SendPropertyChanged("clé");
					this.OncléChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eva", DbType="Int")]
		public System.Nullable<int> eva
		{
			get
			{
				return this._eva;
			}
			set
			{
				if ((this._eva != value))
				{
					this.OnevaChanging(value);
					this.SendPropertyChanging();
					this._eva = value;
					this.SendPropertyChanged("eva");
					this.OnevaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(MAX)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eval", DbType="VarChar(MAX)")]
		public string eval
		{
			get
			{
				return this._eval;
			}
			set
			{
				if ((this._eval != value))
				{
					this.OnevalChanging(value);
					this.SendPropertyChanging();
					this._eval = value;
					this.SendPropertyChanged("eval");
					this.OnevalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Salaire")]
	public partial class Salaire : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _matricule;
		
		private System.Nullable<long> _ancien_;
		
		private System.Nullable<long> _nouveau;
		
		private System.Nullable<System.DateTime> _date_modif;
		
		private int _id;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatriculeChanging(System.Nullable<int> value);
    partial void OnmatriculeChanged();
    partial void Onancien_Changing(System.Nullable<long> value);
    partial void Onancien_Changed();
    partial void OnnouveauChanging(System.Nullable<long> value);
    partial void OnnouveauChanged();
    partial void Ondate_modifChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_modifChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    #endregion
		
		public Salaire()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricule", DbType="Int")]
		public System.Nullable<int> matricule
		{
			get
			{
				return this._matricule;
			}
			set
			{
				if ((this._matricule != value))
				{
					this.OnmatriculeChanging(value);
					this.SendPropertyChanging();
					this._matricule = value;
					this.SendPropertyChanged("matricule");
					this.OnmatriculeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[ancien ]", Storage="_ancien_", DbType="BigInt")]
		public System.Nullable<long> ancien_
		{
			get
			{
				return this._ancien_;
			}
			set
			{
				if ((this._ancien_ != value))
				{
					this.Onancien_Changing(value);
					this.SendPropertyChanging();
					this._ancien_ = value;
					this.SendPropertyChanged("ancien_");
					this.Onancien_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nouveau", DbType="BigInt")]
		public System.Nullable<long> nouveau
		{
			get
			{
				return this._nouveau;
			}
			set
			{
				if ((this._nouveau != value))
				{
					this.OnnouveauChanging(value);
					this.SendPropertyChanging();
					this._nouveau = value;
					this.SendPropertyChanged("nouveau");
					this.OnnouveauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_modif", DbType="DateTime")]
		public System.Nullable<System.DateTime> date_modif
		{
			get
			{
				return this._date_modif;
			}
			set
			{
				if ((this._date_modif != value))
				{
					this.Ondate_modifChanging(value);
					this.SendPropertyChanging();
					this._date_modif = value;
					this.SendPropertyChanged("date_modif");
					this.Ondate_modifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.congé2")]
	public partial class congé2 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _matricule;
		
		private System.Nullable<System.DateTime> _debut;
		
		private System.Nullable<System.DateTime> _fin;
		
		private string _type;
		
		private System.Nullable<long> _nb_j_r;
		
		private System.Data.Linq.Binary _formulaire;
		
		private int _clé;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatriculeChanging(System.Nullable<int> value);
    partial void OnmatriculeChanged();
    partial void OndebutChanging(System.Nullable<System.DateTime> value);
    partial void OndebutChanged();
    partial void OnfinChanging(System.Nullable<System.DateTime> value);
    partial void OnfinChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void Onnb_j_rChanging(System.Nullable<long> value);
    partial void Onnb_j_rChanged();
    partial void OnformulaireChanging(System.Data.Linq.Binary value);
    partial void OnformulaireChanged();
    partial void OncléChanging(int value);
    partial void OncléChanged();
    #endregion
		
		public congé2()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matricule", DbType="Int")]
		public System.Nullable<int> matricule
		{
			get
			{
				return this._matricule;
			}
			set
			{
				if ((this._matricule != value))
				{
					this.OnmatriculeChanging(value);
					this.SendPropertyChanging();
					this._matricule = value;
					this.SendPropertyChanged("matricule");
					this.OnmatriculeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_debut", DbType="Date")]
		public System.Nullable<System.DateTime> debut
		{
			get
			{
				return this._debut;
			}
			set
			{
				if ((this._debut != value))
				{
					this.OndebutChanging(value);
					this.SendPropertyChanging();
					this._debut = value;
					this.SendPropertyChanged("debut");
					this.OndebutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fin", DbType="Date")]
		public System.Nullable<System.DateTime> fin
		{
			get
			{
				return this._fin;
			}
			set
			{
				if ((this._fin != value))
				{
					this.OnfinChanging(value);
					this.SendPropertyChanging();
					this._fin = value;
					this.SendPropertyChanged("fin");
					this.OnfinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(MAX)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nb_j_r", DbType="BigInt")]
		public System.Nullable<long> nb_j_r
		{
			get
			{
				return this._nb_j_r;
			}
			set
			{
				if ((this._nb_j_r != value))
				{
					this.Onnb_j_rChanging(value);
					this.SendPropertyChanging();
					this._nb_j_r = value;
					this.SendPropertyChanged("nb_j_r");
					this.Onnb_j_rChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_formulaire", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary formulaire
		{
			get
			{
				return this._formulaire;
			}
			set
			{
				if ((this._formulaire != value))
				{
					this.OnformulaireChanging(value);
					this.SendPropertyChanging();
					this._formulaire = value;
					this.SendPropertyChanged("formulaire");
					this.OnformulaireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clé", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int clé
		{
			get
			{
				return this._clé;
			}
			set
			{
				if ((this._clé != value))
				{
					this.OncléChanging(value);
					this.SendPropertyChanging();
					this._clé = value;
					this.SendPropertyChanged("clé");
					this.OncléChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
